export { userTable } from "./user.models.js"
export { postTable } from  "./post.models.js"
export { savepostusers } from "./savepost.models.js"
export { quesansTable } from "./queandans.models.js"
export { commentTable } from "./comment.models.js"